services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_pandora
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db_pandora
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pandoradb
      MYSQL_USER: pandoradb_user
      MYSQL_PASSWORD: pandoradb_pass
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_pandora
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
